Copy-edit

diff --git a/ediff-merge-script b/ediff-merge-script
--- a/ediff-merge-script
+++ b/ediff-merge-script
@@ -10,7 +10,7 @@
 # 	cmd = /path/to/git-scripts/ediff-merge-script "$LOCAL" "$REMOTE" "$MERGED" "$BASE"
 # 	trustExitCode = true
 
-## USER CUSTOMAZATION:
+## USER CUSTOMIZATION:
 ## Choose emacs or emacsclient.  emacsclient starts up faster, but emacs gives a
 ## fresh context and avoids cluttering the original emacs with merge buffers.
 _EMACSCLIENT=emacs
@@ -18,14 +18,14 @@ _EMACSCLIENT=emacs
 
 # This script is originally from
 #   http://stackoverflow.com/questions/1817370/using-ediff-as-git-mergetool
-# I have extended so it handles both emacs and emacsclient,
+# I have extended it so it handles both emacs and emacsclient,
 # and made other improvements.
 
 # test args
 if [ ! ${#} -ge 3 ]; then
-  echo 1>&2 "Error: ${0} requires 4 arguments, got ${#}"
+  echo 1>&2 "Error: ${0} requires 3 or 4 arguments, got ${#}"
   echo 1>&2 "Usage: ${0} LOCAL REMOTE MERGED BASE"
-  echo 1>&2 "       (LOCAL, REMOTE, MERGED, BASE can be provided by \`git mergetool'.)"
+  echo 1>&2 "       (LOCAL, REMOTE, MERGED, BASE can be provided by \`git mergetool\`.)"
   exit 1
 fi
 
