Better test and cleanup

diff --git a/git-clone-related b/git-clone-related
--- a/git-clone-related
+++ b/git-clone-related
@@ -165,15 +165,16 @@ else
   fi
   echo "${SCRIPT_NAME}: About to run: git clone -q -b ${REPO_BRANCH} $* ${REPO_URL} ${DESTINATION}"
   # Try twice in case of network lossage.  60 seconds is not enough to clone a branch of the JDK.
-  timeout 180 git clone -q -b "${REPO_BRANCH}" "$@" "${REPO_URL}" "${DESTINATION}" \
-    || { echo "Retrying 'git clone ... ${REPO_URL} ${DESTINATION}' after timeout" \
-      && rm -rf "${DESTINATION}" \
-      && sleep 180 \
-      && { timeout 180 git clone -q -b "${REPO_BRANCH}" "$@" "${REPO_URL}" "${DESTINATION}" \
-        || {
-          echo "${SCRIPT_NAME}: failed: git clone -q -b ${REPO_BRANCH}" "$@" "${REPO_URL} ${DESTINATION}"
-          exit 2
-        }; }; }
+  if ! timeout 180 git clone -q -b "${REPO_BRANCH}" "$@" "${REPO_URL}" "${DESTINATION}"; then
+    echo "Retrying 'git clone ... ${REPO_URL} ${DESTINATION}' after timeout"
+    rm -rf "${DESTINATION}"
+    sleep 180
+    if ! timeout 180 git clone -b "${REPO_BRANCH}" "$@" "${REPO_URL}" "${DESTINATION}"; then
+      echo "${SCRIPT_NAME}: failed: git clone -q -b ${REPO_BRANCH}" "$@" "${REPO_URL} ${DESTINATION}"
+      exit 2
+    fi
+  fi
+
 fi
 
 echo "${SCRIPT_NAME}: ${DESTINATION} is at $(cd "${DESTINATION}" && git rev-parse HEAD)"
