Add diagnostics

diff --git a/git-clone-related b/git-clone-related
--- a/git-clone-related
+++ b/git-clone-related
@@ -56,8 +56,10 @@ if [ "$1" = "--upstream-branch" ]; then
   shift
 fi
 
+SCRIPTNAME="$(basename "$0")"
+
 if [ "$#" -lt 2 ]; then
-  echo "Usage: $0 UPSTREAM_ORG REPO [DESTINATION] [GIT_CLONE_ARGS...]" >&2
+  echo "Usage: ${SCRIPTNAME} UPSTREAM_ORG REPO [DESTINATION] [GIT_CLONE_ARGS...]" >&2
   exit 1
 fi
 
@@ -89,10 +91,11 @@ if [ "$#" -eq 0 ]; then
 fi
 
 if [ -n "$DEBUG" ]; then
-  echo "Entering git-clone-related $UPSTREAM_ORG $REPO_NAME $DESTINATION $*"
+  echo "Entering ${SCRIPTNAME} $UPSTREAM_ORG $REPO_NAME $DESTINATION $*"
+  echo "${SCRIPTNAME}: PWD = ${PWD}"
 fi
 
-echo "In directory $(pwd) :"
+echo "In directory ${PWD} :"
 if [ -d "${DESTINATION}" ]; then
   echo "git-clone-related: destination ${DESTINATION} exists; pulling"
   # Use "cd" because older versions of git (eg, CircleCI) don't support the -C command-line option.
@@ -106,55 +109,72 @@ elif [ -e "${DESTINATION}" ]; then
 else
   SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
 
-  CI_INFO="$SCRIPT_DIR/../plume-scripts/ci-info"
-  if [ ! -f "$CI_INFO" ]; then
-    CI_INFO="$SCRIPT_DIR/../.plume-scripts/ci-info"
-  fi
-  if [ ! -f "$CI_INFO" ]; then
-    CI_INFO="$SCRIPT_DIR/.plume-scripts/ci-info"
-  fi
-  if [ ! -f "$CI_INFO" ]; then
+  # Set PLUME_SCRIPTS.
+  for dir in "../plume-scripts" ".plume-scripts" "../.plume-scripts"; do
+    if [ -d "${SCRIPT_DIR}/${dir}" ]; then
+      PLUME_SCRIPTS="${SCRIPT_DIR}/${dir}"
+    fi
+  done
+  if [ -z "$PLUME_SCRIPTS" ]; then
     (cd "$SCRIPT_DIR" && git clone -q --depth 1 https://github.com/plume-lib/plume-scripts .plume-scripts)
+    PLUME_SCRIPTS="${SCRIPT_DIR}/.plume-scripts"
   fi
+
+  CI_INFO="${PLUME_SCRIPTS}/ci-info"
   if [ ! -f "$CI_INFO" ]; then
     echo "CI_INFO does not exist: $CI_INFO"
     exit 1
   fi
 
   if [ -n "$DEBUG" ]; then
-    echo "About to run ci-info --debug"
+    echo "${SCRIPTNAME}: About to run: ci-info --debug"
     "${CI_INFO}" --debug "${UPSTREAM_ORG}"
-    echo "Ran ci-info --debug"
-    echo "About to run ci-info"
+    echo "${SCRIPTNAME}: Done: ci-info --debug"
+    echo "${SCRIPTNAME}: About to run: ci-info"
+  fi
+  ci_info_output="$("${CI_INFO}" "${UPSTREAM_ORG}")"
+  if [ -n "$DEBUG" ]; then
+    echo "${SCRIPTNAME}: Done: ci-info"
+    echo "---- start of ci-info output ----"
+    # If `set -v` is on, the output will appear doubled, with the first copy preceded by "+ echo ".
+    echo "${ci_info_output}"
+    echo "---- end of ci-info output ----"
+    echo "${SCRIPTNAME}: About to eval ci-info output in ${PWD}"
   fi
 
-  eval "$("${CI_INFO}" "${UPSTREAM_ORG}")"
+  eval "${ci_info_output}"
   if [ -n "$DEBUG" ]; then
-    echo "Finished running ci-info"
+    echo "${SCRIPTNAME}: Done: eval ci-info output in ${PWD}"
   fi
   UPSTREAM_REPO_URL="https://github.com/${UPSTREAM_ORG}/${REPO_NAME}.git"
 
   if [ -n "$DEBUG" ]; then
-    echo "About to run git-find-fork" "${CI_ORGANIZATION}" "${UPSTREAM_ORG}" "${REPO_NAME}"
+    echo "${SCRIPTNAME}: About to run: git-find-fork" "${CI_ORGANIZATION}" "${UPSTREAM_ORG}" "${REPO_NAME}"
   fi
   # REPO_URL is what will be cloned.  It might be the same as UPSTREAM_REPO_URL.
   REPO_URL=$("${SCRIPT_DIR}"/git-find-fork "${CI_ORGANIZATION}" "${UPSTREAM_ORG}" "${REPO_NAME}")
   if [ -n "$DEBUG" ]; then
-    echo "git-find-fork ${CI_ORGANIZATION} ${UPSTREAM_ORG} ${REPO_NAME} => ${REPO_URL}"
+    echo "${SCRIPTNAME}: Done: git-find-fork ${CI_ORGANIZATION} ${UPSTREAM_ORG} ${REPO_NAME} => ${REPO_URL}"
   fi
   if [ -n "$DEBUG" ]; then
-    echo "About to run git-find-branch" "${REPO_URL}" "${CI_BRANCH_NAME}" ${FALLBACK_BRANCH:+"$FALLBACK_BRANCH"}
+    echo "${SCRIPTNAME}: About to run: git-find-branch" "${REPO_URL}" "${CI_BRANCH_NAME}" ${FALLBACK_BRANCH:+"$FALLBACK_BRANCH"}
   fi
   REPO_BRANCH=$("${SCRIPT_DIR}"/git-find-branch "${REPO_URL}" "${CI_BRANCH_NAME}" ${FALLBACK_BRANCH:+"$FALLBACK_BRANCH"})
   if [ -n "$DEBUG" ]; then
-    echo "git-find-branch ${REPO_URL} ${CI_BRANCH_NAME} => ${REPO_BRANCH}"
+    echo "${SCRIPTNAME}: Done: git-find-branch ${REPO_URL} ${CI_BRANCH_NAME} => ${REPO_BRANCH}"
   fi
   if [ "$UPSTREAM_REPO_URL" != "$REPO_URL" ] && [ "$REPO_BRANCH" != "$CI_BRANCH_NAME" ]; then
-    ## Don't use the fallback branch (e.g., master) of the downstream repo
+    ## Don't use the fallback branch (e.g., master) of the downstream repo.
     REPO_URL="$UPSTREAM_REPO_URL"
+    if [ -n "$DEBUG" ]; then
+      echo "${SCRIPTNAME}: About to run: git-find-branch" "${REPO_URL}" "${CI_BRANCH_NAME}" ${FALLBACK_BRANCH:+"$FALLBACK_BRANCH"}
+    fi
     REPO_BRANCH=$("${SCRIPT_DIR}"/git-find-branch "${REPO_URL}" "${CI_BRANCH_NAME}" ${FALLBACK_BRANCH:+"$FALLBACK_BRANCH"})
+    if [ -n "$DEBUG" ]; then
+      echo "${SCRIPTNAME}: Done: git-find-branch" "${REPO_URL}" "${CI_BRANCH_NAME}" ${FALLBACK_BRANCH:+"$FALLBACK_BRANCH"} = > "${REPO_BRANCH}"
+    fi
   fi
-  echo "About to run: git clone -q -b ${REPO_BRANCH} $* ${REPO_URL} ${DESTINATION}"
+  echo "${SCRIPTNAME}: About to run: git clone -q -b ${REPO_BRANCH} $* ${REPO_URL} ${DESTINATION}"
   # Try twice in case of network lossage.  60 seconds is not enough for a branch of the JDK.
   timeout 180 git clone -q -b "${REPO_BRANCH}" "$@" "${REPO_URL}" "${DESTINATION}" \
     || { echo "Retrying 'git clone ... ${REPO_URL} ${DESTINATION}' after timeout" \
@@ -162,8 +182,8 @@ else
       && sleep 180 \
       && { timeout 180 git clone -q -b "${REPO_BRANCH}" "$@" "${REPO_URL}" "${DESTINATION}" \
         || {
-          echo "git-clone-related: failed: git clone -q -b ${REPO_BRANCH}" "$@" "${REPO_URL} ${DESTINATION}"
+          echo "${SCRIPTNAME}: failed: git clone -q -b ${REPO_BRANCH}" "$@" "${REPO_URL} ${DESTINATION}"
           exit 2
         }; }; }
 fi
-echo "git-clone-related: ${DESTINATION} is at $(cd "${DESTINATION}" && git rev-parse HEAD)"
+echo "${SCRIPTNAME}: ${DESTINATION} is at $(cd "${DESTINATION}" && git rev-parse HEAD)"
