Fix Python mistake

diff --git a/resolve-import-conflicts b/resolve-import-conflicts
--- a/resolve-import-conflicts
+++ b/resolve-import-conflicts
@@ -2,15 +2,17 @@
 # bash, not POSIX sh, because of "readarray".
 
 # This script edits files in place to remove conflict markers related to Java
-# imports.  The output includes every `import` statement that is in either of
-# the parents.  This script leaves other conflict markers untouched.
+# imports.  For a given conflict that involves only `import` statements and
+# blank lines, the output includes every `import` statement that is in either
+# of the parents.  This script leaves other conflicts untouched.
+
 # Usage:
 #   resolve-import-conflicts [file ...]
 #
 # The script works on all files given on the command line.
 # If none are given, the script works on all files in or under the current directory.
 #
-# The exit status code is 0 (success) if all conflicts are resolved.
+# The exit status code is 0 (success) if all conflicts are resolved in all the files.
 # The exit status code is 1 (failure) if any conflict remains.
 
 # This script is not a git mergetool.  A git mergetool is given the base, parent 1, and
@@ -34,4 +36,4 @@ for file in "${files[@]}" ; do
   fi
 done
 
-exit $status
+exit "$status"
